### PR TITLE
fix: ensure asdf-plugin-manager works in expected worktree

### LINKED ISSUE #55: add-all is modifying my git repo
**Describe the bug**

example repo: https://github.com/airtonix/broken-asdf-plugin-manager-1-3-1

I've been using the `./setup.sh` in lots of projects for my team members to faceroll all day long.

```sh
test on git master 
> ./setup.sh 

🍙  Installing/Updating ASDF  


🍙  Updating asdf...  

HEAD is now at ccdd47d chore(master): release 0.14.0 (#1641)
Updated asdf to release v0.14.0

🍙  Installing ASDF Plugin Manager 1.3.1  

Plugin named asdf-plugin-manager already added
Location of asdf-plugin-manager plugin: /home/zenobius/.asdf/plugins/asdf-plugin-manager
Updating asdf-plugin-manager to v1.3.1
warning: refname 'v1.3.1' is ambiguous.
warning: refname 'v1.3.1' is ambiguous.
Already on 'v1.3.1'
asdf-plugin-manager 1.3.1 is already installed

🍙  Installing .plugin-versions  

[INFO] Adding: asdf-plugin-manager https://github.com/asdf-community/asdf-plugin-manager.git 6fc3faa
Plugin named asdf-plugin-manager already added
error: Your local changes to the following files would be overwritten by checkout:
        README.md
Please commit your changes or stash them before you switch branches.
Aborting
```

**Steps to reproduce**

```sh
git clone git@github.com:airtonix/broken-asdf-plugin-manager-1-3-1.git
cd broken-asdf-plugin-manager-1-3-1
./setup.sh
```

**Expected behavior**

don't run git in my repo

**Additional context**

it's most likely `checkout_plugin_ref` causing the issue

### PR DESCRIPTION
**Pull request by airtonix**
fixes #55

`--git-dir` doesn't work as by itself, so also include `--worktree`

### CODE REVIEW

File: cli/asdf-plugin-manager.sh [hunk 1]
```diff
@@ -57,11 +57,17 @@ print_git_compare_url() {
...
+    *github*)
+        echo "${provider_url%.*}/compare/${plugin_ref_current}...${plugin_ref_head}"
+        ;;
+    *gitlab*)
+        echo "${provider_url%.*}/-/compare/${plugin_ref_current}...${plugin_ref_head}"
+        ;;
+    *)
+        echo "Unknown provider: ${provider_url}"
+        ;;
+    esac
```
Comment (airtonix) [inline cli/asdf-plugin-manager.sh:70]: image

File: scripts/lint.bash [hunk 2]
```diff
@@ -5,5 +5,7 @@ shellcheck --shell=bash --external-sources \
     lib/* \
     scripts/*
 
+# shellcheck disable=SC2046
+# shellcheck disable=SC2156
```
Comment (airtonix) [inline scripts/lint.bash:9]: image

File: .editorconfig [hunk 3]
```diff
@@ -1,7 +1,7 @@
 root = true
 
 [*]
-indent_style = tab
+indent_style = space
```
Comment (airtonix) [inline .editorconfig:4]: Looks like `scripts/format.bash` and `scripts/lint.bash` can't agree on how to use `.editorconfig`

File: cli/asdf-plugin-manager.sh [hunk 4]
```diff
@@ -70,9 +76,15 @@ export_plugins() {
...
+    local plugin_name
+    local plugin_ref
+    local git_dir
+
     plugin_name="${1}"
     plugin_ref="${2}"
-    git --git-dir "${PLUGINS_REPOS_DIR}/${plugin_name}/.git" checkout "${plugin_ref}" -q
+    git_dir="${PLUGINS_REPOS_DIR}/${plugin_name}"
+
+    git -C "${git_dir}" checkout "${plugin_ref}"
```
Comment (airtonix) [inline cli/asdf-plugin-manager.sh:87]: https://github.com/asdf-community/asdf-plugin-manager/commit/136c63a4dcf16999fe633c32b70d00eb1f9c8a24#r143285680

File: scripts/lint.bash (hunk 2 above)
Comment (aabouzaid) [reply scripts/lint.bash:9]: Please fix them instead of disabling them.

**Comment by its-raj21** [comment]
@aabouzaid, Any idea, when this will be merged.? we are also facing this issue if we aren't using the latest commit ref for the plugins.

**Comment by aabouzaid** [comment]
I've fixed the issue, which will be included in the next release.

File: cli/asdf-plugin-manager.sh [hunk 5]
```diff
@@ -72,7 +78,11 @@ export_plugins() {
 checkout_plugin_ref() {
     plugin_name="${1}"
     plugin_ref="${2}"
-    git --git-dir "${PLUGINS_REPOS_DIR}/${plugin_name}/.git" checkout "${plugin_ref}" -q
+    git_dir="${PLUGINS_REPOS_DIR}/${plugin_name}"
```
Comment (airtonix) [inline cli/asdf-plugin-manager.sh:81]: btw removing `local` now means you're reassigning a global variable, which these are not. just fyi.

Comment (aabouzaid) [reply cli/asdf-plugin-manager.sh:81]: It's only a problem if another global var has the same name.
But in general, I will review all functions vars and make them local to avoid any issues in the future.

Comment (airtonix) [reply cli/asdf-plugin-manager.sh:81]: tbh, it's just easier to use `local`.
